[changelog]
header = "# Changelog\n\n"
body = """
{% if version %}## {{ version }}{% else %}## Unreleased{% endif %}\n
{% for group, commits in commits | group_by(attribute=\"group\") %}
### {{ group }}\n
{% for commit in commits %}
- {{ commit.message | split(pat=\"\\n\") | first }} ({{ commit.id | truncate(length=7, end=\"\") }})
{% endfor %}\n
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
split_commits = true
tag_pattern = "v[0-9].*"

commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Fixes" },
  { message = "^docs", group = "Docs" },
  { message = "^refactor", group = "Refactor" },
  { message = "^perf", group = "Performance" },
  { message = "^test", group = "Tests" },
  { message = "^chore", group = "Chores" }
]
