apiVersion: v1
kind: ConfigMap
metadata:
  name: devbox-app-config
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: devbox
  DB_USER: devbox
  DJANGO_DEBUG: "0"
  ALLOWED_HOSTS: "devbox-app.localhost,backend,backend.devbox-app.svc.cluster.local,localhost,127.0.0.1"
  CORS_ALLOWED_ORIGINS: "http://devbox-app.localhost,http://localhost:8080"
