apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/ihexhubs/devbox-app-backend
    newName: ghcr.io/ihexhubs/devbox-app-backend
    newTag: ihh-devtools-v0.1.0.rc.1-build.3-rev.3
  - name: ghcr.io/ihexhubs/devbox-app-frontend
    newName: ghcr.io/ihexhubs/devbox-app-frontend
    newTag: ihh-devtools-v0.1.0.rc.1-build.3-rev.3
