apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/ihexhubs/devbox-app-backend
    newName: ghcr.io/ihexhubs/devbox-app-backend
    newTag: local
  - name: ghcr.io/ihexhubs/devbox-app-frontend
    newName: ghcr.io/ihexhubs/devbox-app-frontend
    newTag: local

patchesStrategicMerge:
  - patch-backend-service.yaml
  - patch-frontend-service.yaml
